// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjruRWS8TQxUN9KlVEH58tZ_ZcNKtnBJE',
    appId: '1:34065004605:web:4e3de8ef4f7f71506c9254',
    messagingSenderId: '34065004605',
    projectId: 'lab12-it-firestor',
    authDomain: 'lab12-it-firestor.firebaseapp.com',
    storageBucket: 'lab12-it-firestor.appspot.com',
    measurementId: 'G-FGWVBFZ8TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqtx4LpCKg4vOhTBKTLHBxNCZtyMi_1gc',
    appId: '1:34065004605:android:b330eaf34e6c86d76c9254',
    messagingSenderId: '34065004605',
    projectId: 'lab12-it-firestor',
    storageBucket: 'lab12-it-firestor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5BK4uTZv_r59JnCSTLXo7Ifj3xuUvko8',
    appId: '1:34065004605:ios:3d493e7adf26229c6c9254',
    messagingSenderId: '34065004605',
    projectId: 'lab12-it-firestor',
    storageBucket: 'lab12-it-firestor.appspot.com',
    iosClientId: '34065004605-8gfamh27lhblgoqftc9jshm132qvj2ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5BK4uTZv_r59JnCSTLXo7Ifj3xuUvko8',
    appId: '1:34065004605:ios:3d493e7adf26229c6c9254',
    messagingSenderId: '34065004605',
    projectId: 'lab12-it-firestor',
    storageBucket: 'lab12-it-firestor.appspot.com',
    iosClientId: '34065004605-8gfamh27lhblgoqftc9jshm132qvj2ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab12',
  );
}
